"""The C++ runtimes' translation units, as LLVM's CMake build of runtimes/
compiles them for each target and variant: written by
packages/bazel/runtimes.ts from the CMake package's builds of LLVM
23.1.2's, do not edit. bazel/runtimes.bzl makes them libraries.

FLAGS: the flag lists, $(SRC) for the sources' directory and $(CXX) for libc++'s
    headers.
GROUPS: sources compiled alike, (an index of FLAGS, sources).
RUNTIMES: library -> "<target> <variant>" -> indices of GROUPS.
"""

FLAGS = [
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCXXABI_BUILDING_LIBRARY", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(SRC)/libcxxabi/include", "-I$(CXX)", "-fvisibility-inlines-hidden", "-O3", "-DNDEBUG", "-std=c++23", "-fPIC", "-nostdinc++", "-fstrict-aliasing", "-funwind-tables", "-D_DEBUG", "-UNDEBUG", "-fsized-deallocation", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-fvisibility-inlines-hidden", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-fvisibility-inlines-hidden", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCXXABI_BUILDING_LIBRARY", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(SRC)/libcxxabi/include", "-I$(CXX)", "-fvisibility-inlines-hidden", "-O3", "-DNDEBUG", "-std=c++23", "-fPIC", "-nostdinc++", "-fstrict-aliasing", "-fno-exceptions", "-D_DEBUG", "-UNDEBUG", "-fsized-deallocation", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-fvisibility-inlines-hidden", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-fvisibility-inlines-hidden", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-fvisibility-inlines-hidden", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-fno-rtti"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-fvisibility-inlines-hidden", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-fno-rtti", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCXXABI_BUILDING_LIBRARY", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D_LIBCXXABI_LINK_PTHREAD_LIB", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-I$(SRC)/libcxx/src", "-I$(SRC)/libcxxabi/include", "-I$(CXX)", "-mno-outline-atomics", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++23", "-fPIC", "-nostdinc++", "-fstrict-aliasing", "-funwind-tables", "-D_DEBUG", "-UNDEBUG", "-fsized-deallocation", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-mno-outline-atomics", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-mno-outline-atomics", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
    ["-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBUNWIND_HAVE_GETAUXVAL", "-D_LIBUNWIND_HIDE_SYMBOLS", "-D_LIBUNWIND_LINK_DL_LIB", "-D_LIBUNWIND_LINK_PTHREAD_LIB", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-mno-outline-atomics", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++17", "-fPIC", "-funwind-tables", "-nostdinc++", "-D_DEBUG", "-UNDEBUG", "-D_LIBUNWIND_IS_NATIVE_ONLY", "-fno-rtti", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden", "-fstrict-aliasing", "-fno-exceptions", "-fno-rtti"],
    ["-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBUNWIND_HAVE_GETAUXVAL", "-D_LIBUNWIND_HIDE_SYMBOLS", "-D_LIBUNWIND_LINK_DL_LIB", "-D_LIBUNWIND_LINK_PTHREAD_LIB", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-mno-outline-atomics", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-funwind-tables", "-nostdinc++", "-D_DEBUG", "-UNDEBUG", "-D_LIBUNWIND_IS_NATIVE_ONLY", "-fno-rtti", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden", "-std=c99", "-fexceptions"],
    ["-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBUNWIND_HAVE_GETAUXVAL", "-D_LIBUNWIND_HIDE_SYMBOLS", "-D_LIBUNWIND_LINK_DL_LIB", "-D_LIBUNWIND_LINK_PTHREAD_LIB", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-O3", "-DNDEBUG", "-fPIC", "-funwind-tables", "-nostdinc++", "-D_DEBUG", "-UNDEBUG", "-D_LIBUNWIND_IS_NATIVE_ONLY", "-fno-rtti", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden"],
    ["-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/compiler-rt/lib", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++17", "-fPIC", "-fno-builtin", "-fno-exceptions", "-fomit-frame-pointer", "-funwind-tables", "-fno-stack-protector", "-fno-sanitize=safe-stack", "-fvisibility=hidden", "-fno-lto", "-O3", "-gline-tables-only", "-ftrivial-auto-var-init=pattern", "-nostdinc++", "-fno-rtti"],
    ["-DHAVE_RPC_XDR_H=1", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/compiler-rt/lib", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++17", "-fPIC", "-fno-builtin", "-fno-exceptions", "-fomit-frame-pointer", "-funwind-tables", "-fno-stack-protector", "-fno-sanitize=safe-stack", "-fvisibility=hidden", "-fno-lto", "-O3", "-gline-tables-only", "-ftrivial-auto-var-init=pattern", "-nostdinc++", "-fno-rtti"],
    ["-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/compiler-rt/lib", "-I$(SRC)/compiler-rt/include", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++17", "-fPIC", "-fno-builtin", "-fno-exceptions", "-fomit-frame-pointer", "-funwind-tables", "-fno-stack-protector", "-fno-sanitize=safe-stack", "-fvisibility=hidden", "-fno-lto", "-O3", "-gline-tables-only", "-ftrivial-auto-var-init=pattern", "-nostdinc++", "-fno-rtti"],
    ["-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/compiler-rt/lib", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++17", "-fno-lto", "-fPIC", "-fno-builtin", "-fno-exceptions", "-fomit-frame-pointer", "-funwind-tables", "-fno-stack-protector", "-fno-sanitize=safe-stack", "-fvisibility=hidden", "-O3", "-gline-tables-only", "-ftrivial-auto-var-init=pattern", "-nostdinc++", "-fno-rtti", "-fPIE", "-ffreestanding"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCXXABI_BUILDING_LIBRARY", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D_LIBCXXABI_LINK_PTHREAD_LIB", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-I$(SRC)/libcxx/src", "-I$(SRC)/libcxxabi/include", "-I$(CXX)", "-mno-outline-atomics", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++23", "-fPIC", "-nostdinc++", "-fstrict-aliasing", "-fno-exceptions", "-D_DEBUG", "-UNDEBUG", "-fsized-deallocation", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-mno-outline-atomics", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-mno-outline-atomics", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-mno-outline-atomics", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-fno-rtti"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-mno-outline-atomics", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-fno-rtti", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_FILE_OFFSET_BITS=64", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCXXABI_BUILDING_LIBRARY", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-I$(SRC)/libcxx/src", "-I$(SRC)/libcxxabi/include", "-I$(CXX)", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++23", "-nostdinc++", "-fstrict-aliasing", "-funwind-tables", "-D_DEBUG", "-UNDEBUG", "-fsized-deallocation", "-fvisibility-global-new-delete=force-hidden"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_FILE_OFFSET_BITS=64", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_FILE_OFFSET_BITS=64", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
    ["-D_FILE_OFFSET_BITS=64", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBUNWIND_HIDE_SYMBOLS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++17", "-funwind-tables", "-nostdinc++", "-D_DEBUG", "-UNDEBUG", "-D_LIBUNWIND_IS_NATIVE_ONLY", "-fno-rtti", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden", "-fstrict-aliasing", "-fno-exceptions", "-fno-rtti"],
    ["-D_FILE_OFFSET_BITS=64", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBUNWIND_HIDE_SYMBOLS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-funwind-tables", "-nostdinc++", "-D_DEBUG", "-UNDEBUG", "-D_LIBUNWIND_IS_NATIVE_ONLY", "-fno-rtti", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden", "-std=c99", "-fexceptions"],
    ["-D_FILE_OFFSET_BITS=64", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBUNWIND_HIDE_SYMBOLS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-O3", "-DNDEBUG", "-funwind-tables", "-nostdinc++", "-D_DEBUG", "-UNDEBUG", "-D_LIBUNWIND_IS_NATIVE_ONLY", "-fno-rtti", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_FILE_OFFSET_BITS=64", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCXXABI_BUILDING_LIBRARY", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-I$(SRC)/libcxx/src", "-I$(SRC)/libcxxabi/include", "-I$(CXX)", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++23", "-nostdinc++", "-fstrict-aliasing", "-fno-exceptions", "-D_DEBUG", "-UNDEBUG", "-fsized-deallocation", "-fvisibility-global-new-delete=force-hidden"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_FILE_OFFSET_BITS=64", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_FILE_OFFSET_BITS=64", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_FILE_OFFSET_BITS=64", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-fno-rtti"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_FILE_OFFSET_BITS=64", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-fno-rtti", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCXXABI_BUILDING_LIBRARY", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D_LIBCXXABI_LINK_PTHREAD_LIB", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-I$(SRC)/libcxx/src", "-I$(SRC)/libcxxabi/include", "-I$(CXX)", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++23", "-fPIC", "-nostdinc++", "-fstrict-aliasing", "-funwind-tables", "-D_DEBUG", "-UNDEBUG", "-fsized-deallocation", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
    ["-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBUNWIND_HAVE_GETAUXVAL", "-D_LIBUNWIND_HIDE_SYMBOLS", "-D_LIBUNWIND_LINK_DL_LIB", "-D_LIBUNWIND_LINK_PTHREAD_LIB", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++17", "-fPIC", "-funwind-tables", "-nostdinc++", "-D_DEBUG", "-UNDEBUG", "-D_LIBUNWIND_IS_NATIVE_ONLY", "-fno-rtti", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden", "-fstrict-aliasing", "-fno-exceptions", "-fno-rtti"],
    ["-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBUNWIND_HAVE_GETAUXVAL", "-D_LIBUNWIND_HIDE_SYMBOLS", "-D_LIBUNWIND_LINK_DL_LIB", "-D_LIBUNWIND_LINK_PTHREAD_LIB", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-funwind-tables", "-nostdinc++", "-D_DEBUG", "-UNDEBUG", "-D_LIBUNWIND_IS_NATIVE_ONLY", "-fno-rtti", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden", "-std=c99", "-fexceptions"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCXXABI_BUILDING_LIBRARY", "-D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS", "-D_LIBCXXABI_LINK_PTHREAD_LIB", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libunwind/include", "-I$(SRC)/libcxx/src", "-I$(SRC)/libcxxabi/include", "-I$(CXX)", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-std=c++23", "-fPIC", "-nostdinc++", "-fstrict-aliasing", "-fno-exceptions", "-D_DEBUG", "-UNDEBUG", "-fsized-deallocation", "-fvisibility=hidden", "-fvisibility-global-new-delete=force-hidden"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-DLIBC_NAMESPACE=__llvm_libc_common_utils", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(SRC)/libcxx/src", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-isystem", "$(SRC)/libc", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-fno-rtti"],
    ["-DLIBCXX_BUILDING_LIBCXXABI", "-D_LIBCPP_AVAILABILITY_MINIMUM_HEADER_VERSION=2", "-D_LIBCPP_BUILDING_LIBRARY", "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\"", "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER", "-D_LIBCPP_LINK_PTHREAD_LIB", "-D_LIBCPP_LINK_RT_LIB", "-D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-I$(CXX)", "-I$(SRC)/libcxxabi/include", "-fvisibility-inlines-hidden", "-ffunction-sections", "-fdata-sections", "-O3", "-DNDEBUG", "-fPIC", "-std=c++26", "-faligned-allocation", "-nostdinc++", "-fvisibility-inlines-hidden", "-fvisibility=hidden", "-fsized-deallocation", "-fno-exceptions", "-fno-rtti", "-D_LIBCPP_ENABLE_EXPERIMENTAL"],
]

GROUPS = [
    (0, [
        "libcxxabi/src/abort_message.cpp",
        "libcxxabi/src/cxa_aux_runtime.cpp",
        "libcxxabi/src/cxa_default_handlers.cpp",
        "libcxxabi/src/cxa_demangle.cpp",
        "libcxxabi/src/cxa_exception.cpp",
        "libcxxabi/src/cxa_exception_storage.cpp",
        "libcxxabi/src/cxa_guard.cpp",
        "libcxxabi/src/cxa_handlers.cpp",
        "libcxxabi/src/cxa_personality.cpp",
        "libcxxabi/src/cxa_vector.cpp",
        "libcxxabi/src/cxa_virtual.cpp",
        "libcxxabi/src/fallback_malloc.cpp",
        "libcxxabi/src/private_typeinfo.cpp",
        "libcxxabi/src/stdlib_exception.cpp",
        "libcxxabi/src/stdlib_new_delete.cpp",
        "libcxxabi/src/stdlib_stdexcept.cpp",
        "libcxxabi/src/stdlib_typeinfo.cpp",
    ]),
    (1, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (2, [
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
    ]),
    (3, [
        "libcxxabi/src/abort_message.cpp",
        "libcxxabi/src/cxa_aux_runtime.cpp",
        "libcxxabi/src/cxa_default_handlers.cpp",
        "libcxxabi/src/cxa_demangle.cpp",
        "libcxxabi/src/cxa_exception_storage.cpp",
        "libcxxabi/src/cxa_guard.cpp",
        "libcxxabi/src/cxa_handlers.cpp",
        "libcxxabi/src/cxa_noexception.cpp",
        "libcxxabi/src/cxa_vector.cpp",
        "libcxxabi/src/cxa_virtual.cpp",
        "libcxxabi/src/fallback_malloc.cpp",
        "libcxxabi/src/private_typeinfo.cpp",
        "libcxxabi/src/stdlib_exception.cpp",
        "libcxxabi/src/stdlib_new_delete.cpp",
        "libcxxabi/src/stdlib_stdexcept.cpp",
        "libcxxabi/src/stdlib_typeinfo.cpp",
    ]),
    (4, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (5, [
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
    ]),
    (6, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (7, [
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
    ]),
    (8, [
        "libcxxabi/src/abort_message.cpp",
        "libcxxabi/src/cxa_aux_runtime.cpp",
        "libcxxabi/src/cxa_default_handlers.cpp",
        "libcxxabi/src/cxa_demangle.cpp",
        "libcxxabi/src/cxa_exception.cpp",
        "libcxxabi/src/cxa_exception_storage.cpp",
        "libcxxabi/src/cxa_guard.cpp",
        "libcxxabi/src/cxa_handlers.cpp",
        "libcxxabi/src/cxa_personality.cpp",
        "libcxxabi/src/cxa_thread_atexit.cpp",
        "libcxxabi/src/cxa_vector.cpp",
        "libcxxabi/src/cxa_virtual.cpp",
        "libcxxabi/src/fallback_malloc.cpp",
        "libcxxabi/src/private_typeinfo.cpp",
        "libcxxabi/src/stdlib_exception.cpp",
        "libcxxabi/src/stdlib_new_delete.cpp",
        "libcxxabi/src/stdlib_stdexcept.cpp",
        "libcxxabi/src/stdlib_typeinfo.cpp",
    ]),
    (9, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (10, [
        "libcxx/src/experimental/chrono_exception.cpp",
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
        "libcxx/src/experimental/time_zone.cpp",
        "libcxx/src/experimental/tzdb.cpp",
        "libcxx/src/experimental/tzdb_list.cpp",
    ]),
    (11, [
        "libunwind/src/Unwind-EHABI.cpp",
        "libunwind/src/Unwind-seh.cpp",
        "libunwind/src/libunwind.cpp",
    ]),
    (12, [
        "libunwind/src/Unwind-sjlj.c",
        "libunwind/src/Unwind-wasm.c",
        "libunwind/src/UnwindLevel1-gcc-ext.c",
        "libunwind/src/UnwindLevel1.c",
    ]),
    (13, [
        "libunwind/src/UnwindRegistersRestore.S",
        "libunwind/src/UnwindRegistersSave.S",
    ]),
    (14, [
        "compiler-rt/lib/interception/interception_aix.cpp",
        "compiler-rt/lib/interception/interception_linux.cpp",
        "compiler-rt/lib/interception/interception_mac.cpp",
        "compiler-rt/lib/interception/interception_type_test.cpp",
        "compiler-rt/lib/interception/interception_win.cpp",
    ]),
    (15, [
        "compiler-rt/lib/sanitizer_common/sancov_flags.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_allocator.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_allocator_checks.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_allocator_report.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_chained_origin_depot.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_common.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_common_libcdep.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_coverage_fuchsia.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_coverage_libcdep_new.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_coverage_win_sections.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_deadlock_detector1.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_deadlock_detector2.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_dl.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_errno.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_file.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_flag_parser.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_flags.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_haiku.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_libc.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_libignore.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_linux_libcdep.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_linux_s390.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_mac.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_mac_libcdep.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_mutex.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_netbsd.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_freebsd.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_linux.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_netbsd.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_solaris.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_posix.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_posix_libcdep.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_printf.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_procmaps_bsd.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_procmaps_common.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_procmaps_fuchsia.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_procmaps_haiku.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_procmaps_linux.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_procmaps_mac.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_procmaps_solaris.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_range.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_solaris.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_stack_store.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_stackdepot.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_stacktrace.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_libcdep.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_printer.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_sparc.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_fuchsia.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_mac.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_netbsd_libcdep.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_win.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_suppressions.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_symbolizer.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libbacktrace.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_mac.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup_fuchsia.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_posix_libcdep.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report_fuchsia.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_win.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_termination.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_thread_arg_retval.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_thread_history.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_thread_registry.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_tls_get_addr.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_type_traits.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_unwind_aix.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_unwind_fuchsia.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_unwind_linux_libcdep.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_unwind_win.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_win.cpp",
        "compiler-rt/lib/sanitizer_common/sanitizer_win_interception.cpp",
    ]),
    (16, [
        "compiler-rt/lib/ubsan/ubsan_diag.cpp",
        "compiler-rt/lib/ubsan/ubsan_flags.cpp",
        "compiler-rt/lib/ubsan/ubsan_handlers.cpp",
        "compiler-rt/lib/ubsan/ubsan_init.cpp",
        "compiler-rt/lib/ubsan/ubsan_monitor.cpp",
        "compiler-rt/lib/ubsan/ubsan_value.cpp",
    ]),
    (17, [
        "compiler-rt/lib/msan/msan.cpp",
        "compiler-rt/lib/msan/msan_allocator.cpp",
        "compiler-rt/lib/msan/msan_chained_origin_depot.cpp",
        "compiler-rt/lib/msan/msan_dl.cpp",
        "compiler-rt/lib/msan/msan_interceptors.cpp",
        "compiler-rt/lib/msan/msan_linux.cpp",
        "compiler-rt/lib/msan/msan_poisoning.cpp",
        "compiler-rt/lib/msan/msan_report.cpp",
        "compiler-rt/lib/msan/msan_thread.cpp",
    ]),
    (17, [
        "compiler-rt/lib/msan/msan_new_delete.cpp",
    ]),
    (18, [
        "libcxxabi/src/abort_message.cpp",
        "libcxxabi/src/cxa_aux_runtime.cpp",
        "libcxxabi/src/cxa_default_handlers.cpp",
        "libcxxabi/src/cxa_demangle.cpp",
        "libcxxabi/src/cxa_exception_storage.cpp",
        "libcxxabi/src/cxa_guard.cpp",
        "libcxxabi/src/cxa_handlers.cpp",
        "libcxxabi/src/cxa_noexception.cpp",
        "libcxxabi/src/cxa_thread_atexit.cpp",
        "libcxxabi/src/cxa_vector.cpp",
        "libcxxabi/src/cxa_virtual.cpp",
        "libcxxabi/src/fallback_malloc.cpp",
        "libcxxabi/src/private_typeinfo.cpp",
        "libcxxabi/src/stdlib_exception.cpp",
        "libcxxabi/src/stdlib_new_delete.cpp",
        "libcxxabi/src/stdlib_stdexcept.cpp",
        "libcxxabi/src/stdlib_typeinfo.cpp",
    ]),
    (19, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (20, [
        "libcxx/src/experimental/chrono_exception.cpp",
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
        "libcxx/src/experimental/time_zone.cpp",
        "libcxx/src/experimental/tzdb.cpp",
        "libcxx/src/experimental/tzdb_list.cpp",
    ]),
    (21, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (22, [
        "libcxx/src/experimental/chrono_exception.cpp",
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
        "libcxx/src/experimental/time_zone.cpp",
        "libcxx/src/experimental/tzdb.cpp",
        "libcxx/src/experimental/tzdb_list.cpp",
    ]),
    (23, [
        "libcxxabi/src/abort_message.cpp",
        "libcxxabi/src/cxa_aux_runtime.cpp",
        "libcxxabi/src/cxa_default_handlers.cpp",
        "libcxxabi/src/cxa_demangle.cpp",
        "libcxxabi/src/cxa_exception.cpp",
        "libcxxabi/src/cxa_exception_storage.cpp",
        "libcxxabi/src/cxa_guard.cpp",
        "libcxxabi/src/cxa_handlers.cpp",
        "libcxxabi/src/cxa_personality.cpp",
        "libcxxabi/src/cxa_vector.cpp",
        "libcxxabi/src/cxa_virtual.cpp",
        "libcxxabi/src/fallback_malloc.cpp",
        "libcxxabi/src/private_typeinfo.cpp",
        "libcxxabi/src/stdlib_exception.cpp",
        "libcxxabi/src/stdlib_new_delete.cpp",
        "libcxxabi/src/stdlib_stdexcept.cpp",
        "libcxxabi/src/stdlib_typeinfo.cpp",
    ]),
    (24, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/support/win32/compiler_rt_shims.cpp",
        "libcxx/src/support/win32/locale_win32.cpp",
        "libcxx/src/support/win32/support.cpp",
        "libcxx/src/support/win32/thread_win32.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (25, [
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
    ]),
    (26, [
        "libunwind/src/Unwind-EHABI.cpp",
        "libunwind/src/Unwind-seh.cpp",
        "libunwind/src/libunwind.cpp",
    ]),
    (27, [
        "libunwind/src/Unwind-sjlj.c",
        "libunwind/src/Unwind-wasm.c",
        "libunwind/src/UnwindLevel1-gcc-ext.c",
        "libunwind/src/UnwindLevel1.c",
    ]),
    (28, [
        "libunwind/src/UnwindRegistersRestore.S",
        "libunwind/src/UnwindRegistersSave.S",
    ]),
    (29, [
        "libcxxabi/src/abort_message.cpp",
        "libcxxabi/src/cxa_aux_runtime.cpp",
        "libcxxabi/src/cxa_default_handlers.cpp",
        "libcxxabi/src/cxa_demangle.cpp",
        "libcxxabi/src/cxa_exception_storage.cpp",
        "libcxxabi/src/cxa_guard.cpp",
        "libcxxabi/src/cxa_handlers.cpp",
        "libcxxabi/src/cxa_noexception.cpp",
        "libcxxabi/src/cxa_vector.cpp",
        "libcxxabi/src/cxa_virtual.cpp",
        "libcxxabi/src/fallback_malloc.cpp",
        "libcxxabi/src/private_typeinfo.cpp",
        "libcxxabi/src/stdlib_exception.cpp",
        "libcxxabi/src/stdlib_new_delete.cpp",
        "libcxxabi/src/stdlib_stdexcept.cpp",
        "libcxxabi/src/stdlib_typeinfo.cpp",
    ]),
    (30, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/support/win32/compiler_rt_shims.cpp",
        "libcxx/src/support/win32/locale_win32.cpp",
        "libcxx/src/support/win32/support.cpp",
        "libcxx/src/support/win32/thread_win32.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (31, [
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
    ]),
    (32, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/support/win32/compiler_rt_shims.cpp",
        "libcxx/src/support/win32/locale_win32.cpp",
        "libcxx/src/support/win32/support.cpp",
        "libcxx/src/support/win32/thread_win32.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (33, [
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
    ]),
    (34, [
        "libcxxabi/src/abort_message.cpp",
        "libcxxabi/src/cxa_aux_runtime.cpp",
        "libcxxabi/src/cxa_default_handlers.cpp",
        "libcxxabi/src/cxa_demangle.cpp",
        "libcxxabi/src/cxa_exception.cpp",
        "libcxxabi/src/cxa_exception_storage.cpp",
        "libcxxabi/src/cxa_guard.cpp",
        "libcxxabi/src/cxa_handlers.cpp",
        "libcxxabi/src/cxa_personality.cpp",
        "libcxxabi/src/cxa_thread_atexit.cpp",
        "libcxxabi/src/cxa_vector.cpp",
        "libcxxabi/src/cxa_virtual.cpp",
        "libcxxabi/src/fallback_malloc.cpp",
        "libcxxabi/src/private_typeinfo.cpp",
        "libcxxabi/src/stdlib_exception.cpp",
        "libcxxabi/src/stdlib_new_delete.cpp",
        "libcxxabi/src/stdlib_stdexcept.cpp",
        "libcxxabi/src/stdlib_typeinfo.cpp",
    ]),
    (35, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (36, [
        "libcxx/src/experimental/chrono_exception.cpp",
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
        "libcxx/src/experimental/time_zone.cpp",
        "libcxx/src/experimental/tzdb.cpp",
        "libcxx/src/experimental/tzdb_list.cpp",
    ]),
    (37, [
        "libunwind/src/Unwind-EHABI.cpp",
        "libunwind/src/Unwind-seh.cpp",
        "libunwind/src/libunwind.cpp",
    ]),
    (38, [
        "libunwind/src/Unwind-sjlj.c",
        "libunwind/src/Unwind-wasm.c",
        "libunwind/src/UnwindLevel1-gcc-ext.c",
        "libunwind/src/UnwindLevel1.c",
    ]),
    (39, [
        "libcxxabi/src/abort_message.cpp",
        "libcxxabi/src/cxa_aux_runtime.cpp",
        "libcxxabi/src/cxa_default_handlers.cpp",
        "libcxxabi/src/cxa_demangle.cpp",
        "libcxxabi/src/cxa_exception_storage.cpp",
        "libcxxabi/src/cxa_guard.cpp",
        "libcxxabi/src/cxa_handlers.cpp",
        "libcxxabi/src/cxa_noexception.cpp",
        "libcxxabi/src/cxa_thread_atexit.cpp",
        "libcxxabi/src/cxa_vector.cpp",
        "libcxxabi/src/cxa_virtual.cpp",
        "libcxxabi/src/fallback_malloc.cpp",
        "libcxxabi/src/private_typeinfo.cpp",
        "libcxxabi/src/stdlib_exception.cpp",
        "libcxxabi/src/stdlib_new_delete.cpp",
        "libcxxabi/src/stdlib_stdexcept.cpp",
        "libcxxabi/src/stdlib_typeinfo.cpp",
    ]),
    (40, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (41, [
        "libcxx/src/experimental/chrono_exception.cpp",
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
        "libcxx/src/experimental/time_zone.cpp",
        "libcxx/src/experimental/tzdb.cpp",
        "libcxx/src/experimental/tzdb_list.cpp",
    ]),
    (42, [
        "libcxx/src/algorithm.cpp",
        "libcxx/src/any.cpp",
        "libcxx/src/atomic.cpp",
        "libcxx/src/barrier.cpp",
        "libcxx/src/bind.cpp",
        "libcxx/src/call_once.cpp",
        "libcxx/src/charconv.cpp",
        "libcxx/src/chrono.cpp",
        "libcxx/src/condition_variable.cpp",
        "libcxx/src/condition_variable_destructor.cpp",
        "libcxx/src/error_category.cpp",
        "libcxx/src/exception.cpp",
        "libcxx/src/expected.cpp",
        "libcxx/src/filesystem/directory_entry.cpp",
        "libcxx/src/filesystem/directory_iterator.cpp",
        "libcxx/src/filesystem/filesystem_clock.cpp",
        "libcxx/src/filesystem/filesystem_error.cpp",
        "libcxx/src/filesystem/operations.cpp",
        "libcxx/src/filesystem/path.cpp",
        "libcxx/src/fstream.cpp",
        "libcxx/src/functional.cpp",
        "libcxx/src/future.cpp",
        "libcxx/src/hash.cpp",
        "libcxx/src/ios.cpp",
        "libcxx/src/ios.instantiations.cpp",
        "libcxx/src/iostream.cpp",
        "libcxx/src/locale.cpp",
        "libcxx/src/memory.cpp",
        "libcxx/src/memory_resource.cpp",
        "libcxx/src/mutex.cpp",
        "libcxx/src/mutex_destructor.cpp",
        "libcxx/src/new_handler.cpp",
        "libcxx/src/new_helpers.cpp",
        "libcxx/src/optional.cpp",
        "libcxx/src/ostream.cpp",
        "libcxx/src/print.cpp",
        "libcxx/src/random.cpp",
        "libcxx/src/random_shuffle.cpp",
        "libcxx/src/regex.cpp",
        "libcxx/src/ryu/d2fixed.cpp",
        "libcxx/src/ryu/d2s.cpp",
        "libcxx/src/ryu/f2s.cpp",
        "libcxx/src/shared_mutex.cpp",
        "libcxx/src/stdexcept.cpp",
        "libcxx/src/string.cpp",
        "libcxx/src/strstream.cpp",
        "libcxx/src/system_error.cpp",
        "libcxx/src/text_encoding.cpp",
        "libcxx/src/thread.cpp",
        "libcxx/src/typeinfo.cpp",
        "libcxx/src/valarray.cpp",
        "libcxx/src/variant.cpp",
        "libcxx/src/vector.cpp",
        "libcxx/src/verbose_abort.cpp",
    ]),
    (43, [
        "libcxx/src/experimental/chrono_exception.cpp",
        "libcxx/src/experimental/keep.cpp",
        "libcxx/src/experimental/log_hardening_failure.cpp",
        "libcxx/src/experimental/time_zone.cpp",
        "libcxx/src/experimental/tzdb.cpp",
        "libcxx/src/experimental/tzdb_list.cpp",
    ]),
]

RUNTIMES = {
    "cxx": {
        "aarch64-apple-darwin default": [0, 1],
        "aarch64-apple-darwin noexcept": [3, 4],
        "aarch64-apple-darwin nortti": [3, 6],
        "aarch64-unknown-linux-gnu default": [8, 9],
        "aarch64-unknown-linux-gnu noexcept": [19, 20],
        "aarch64-unknown-linux-gnu nortti": [19, 22],
        "aarch64-unknown-linux-musl default": [8, 9],
        "aarch64-unknown-linux-musl noexcept": [19, 20],
        "aarch64-unknown-linux-musl nortti": [19, 22],
        "aarch64-w64-mingw32 default": [24, 25],
        "aarch64-w64-mingw32 noexcept": [30, 31],
        "aarch64-w64-mingw32 nortti": [30, 33],
        "x86_64-apple-darwin default": [0, 1],
        "x86_64-apple-darwin noexcept": [3, 4],
        "x86_64-apple-darwin nortti": [3, 6],
        "x86_64-unknown-linux-gnu default": [35, 36],
        "x86_64-unknown-linux-gnu noexcept": [40, 41],
        "x86_64-unknown-linux-gnu nortti": [40, 43],
        "x86_64-unknown-linux-musl default": [35, 36],
        "x86_64-unknown-linux-musl noexcept": [40, 41],
        "x86_64-unknown-linux-musl nortti": [40, 43],
        "x86_64-w64-mingw32 default": [24, 25],
        "x86_64-w64-mingw32 noexcept": [30, 31],
        "x86_64-w64-mingw32 nortti": [30, 33],
    },
    "cxx_experimental": {
        "aarch64-apple-darwin default": [2],
        "aarch64-apple-darwin noexcept": [5],
        "aarch64-apple-darwin nortti": [7],
        "aarch64-unknown-linux-gnu default": [10],
        "aarch64-unknown-linux-gnu noexcept": [21],
        "aarch64-unknown-linux-gnu nortti": [23],
        "aarch64-unknown-linux-musl default": [10],
        "aarch64-unknown-linux-musl noexcept": [21],
        "aarch64-unknown-linux-musl nortti": [23],
        "aarch64-w64-mingw32 default": [26],
        "aarch64-w64-mingw32 noexcept": [32],
        "aarch64-w64-mingw32 nortti": [34],
        "x86_64-apple-darwin default": [2],
        "x86_64-apple-darwin noexcept": [5],
        "x86_64-apple-darwin nortti": [7],
        "x86_64-unknown-linux-gnu default": [37],
        "x86_64-unknown-linux-gnu noexcept": [42],
        "x86_64-unknown-linux-gnu nortti": [44],
        "x86_64-unknown-linux-musl default": [37],
        "x86_64-unknown-linux-musl noexcept": [42],
        "x86_64-unknown-linux-musl nortti": [44],
        "x86_64-w64-mingw32 default": [26],
        "x86_64-w64-mingw32 noexcept": [32],
        "x86_64-w64-mingw32 nortti": [34],
    },
    "msan": {
        "aarch64-unknown-linux-gnu msan": [14, 15, 16, 17],
        "x86_64-unknown-linux-gnu msan": [14, 15, 16, 17],
    },
    "msan_cxx": {
        "aarch64-unknown-linux-gnu msan": [18],
        "x86_64-unknown-linux-gnu msan": [18],
    },
    "unwind": {
        "aarch64-unknown-linux-gnu default": [11, 12, 13],
        "aarch64-unknown-linux-gnu noexcept": [11, 12, 13],
        "aarch64-unknown-linux-gnu nortti": [11, 12, 13],
        "aarch64-unknown-linux-musl default": [11, 12, 13],
        "aarch64-unknown-linux-musl noexcept": [11, 12, 13],
        "aarch64-unknown-linux-musl nortti": [11, 12, 13],
        "aarch64-w64-mingw32 default": [27, 28, 29],
        "aarch64-w64-mingw32 noexcept": [27, 28, 29],
        "aarch64-w64-mingw32 nortti": [27, 28, 29],
        "x86_64-unknown-linux-gnu default": [13, 38, 39],
        "x86_64-unknown-linux-gnu noexcept": [13, 38, 39],
        "x86_64-unknown-linux-gnu nortti": [13, 38, 39],
        "x86_64-unknown-linux-musl default": [13, 38, 39],
        "x86_64-unknown-linux-musl noexcept": [13, 38, 39],
        "x86_64-unknown-linux-musl nortti": [13, 38, 39],
        "x86_64-w64-mingw32 default": [27, 28, 29],
        "x86_64-w64-mingw32 noexcept": [27, 28, 29],
        "x86_64-w64-mingw32 nortti": [27, 28, 29],
    },
}
