/// The conda packages of a release, from its archives, for the clice conda
/// channel (clice-io/conda, https://conda.clice.io):
///
///   xclang            one per host subdir: the host's archive as it is, every
///                     target included, and the activation scripts that put
///                     its bin/ in PATH
///   llvm-option-inc   noarch: the option tables, in include/
///
/// The toolchain installs under $PREFIX/opt/xclang; nothing goes to
/// $PREFIX/bin, so conda-forge's clang is left alone. Versions are the
/// release's (23.1.2.1); a build number counts packaging fixes only.
///
///   node scripts/conda.ts --dist <release assets> --version <x.y.z.r>
///     [--build n] [--rattler-build <path>] [--hosts <triple>,...]
///     [--option-inc] --out <dir>

import fs from "node:fs";
import path from "node:path";
import { parseArgs } from "node:util";
import * as common from "./common.ts";

const { values } = parseArgs({
  options: {
    dist: { type: "string" },
    version: { type: "string" },
    "rattler-build": { type: "string", default: "rattler-build" },
    out: { type: "string" },
    build: { type: "string", default: "0" },
    /// The hosts to package (all by default), and whether llvm-option-inc
    /// comes along: CI packages each host on a machine of its own.
    hosts: { type: "string" },
    "option-inc": { type: "boolean", default: false },
    /// zstd's level for the .conda files: 22 makes them as small as the
    /// release's xz (19 leaves them a fifth larger), at some minutes each.
    compression: { type: "string", default: "22" },
  },
});
if (!values.dist || !values.version || !values.out) {
  common.fail("--dist <release assets> --version <x.y.z.r> [--build n] [--rattler-build <path>] --out <dir>");
}
const version = values.version;
const dist = path.resolve(values.dist);
const out = path.resolve(values.out);
const work = path.join(common.WORK, "conda");
fs.rmSync(work, { recursive: true, force: true });

const SUBDIRS: Record<string, string> = {
  "x86_64-unknown-linux-gnu": "linux-64",
  "aarch64-unknown-linux-gnu": "linux-aarch64",
  "x86_64-w64-mingw32": "win-64",
  "aarch64-w64-mingw32": "win-arm64",
  "x86_64-apple-darwin": "osx-64",
  "aarch64-apple-darwin": "osx-arm64",
};
/// libc++, compiler-rt and LLVM's tools; glibc 2.17 (Linux targets);
/// mingw-w64 and winpthreads (Windows targets).
const LICENSE = "Apache-2.0 WITH LLVM-exception AND LGPL-2.1-or-later AND ZPL-2.1 AND MIT";

interface Package {
  name: string;
  stage: string;
  subdir?: string;
  license: string;
  summary: string;
}
const packages: Package[] = [];

const hosts = values.hosts ? values.hosts.split(",").map((h) => common.target(h)) : common.TARGETS;
for (const host of hosts) {
  const archive = path.join(dist, `xclang-${version}-${host.triple}.tar.xz`);
  if (!fs.existsSync(archive)) common.fail(`missing ${archive}`);
  const stage = path.join(work, "stage", `xclang-${SUBDIRS[host.triple]}`);
  fs.mkdirSync(path.join(stage, "opt"), { recursive: true });
  common.run("tar", ["-C", path.join(stage, "opt"), "-xJf", archive]);
  for (const phase of ["activate", "deactivate"]) {
    for (const ext of host.os === "mingw" ? ["bat", "ps1"] : ["sh"]) {
      const to = path.join(stage, "etc", "conda", `${phase}.d`, `xclang.${ext}`);
      fs.mkdirSync(path.dirname(to), { recursive: true });
      fs.copyFileSync(path.join(common.ROOT, "conda", `${phase}.${ext}`), to);
    }
  }
  packages.push({
    name: "xclang",
    stage,
    subdir: SUBDIRS[host.triple],
    license: LICENSE,
    summary: "A self-contained clang toolchain for six targets: clang, lld and the LLVM tools, PGO and ThinLTO optimized",
  });
}

if (values["option-inc"]) {
  const archive = path.join(dist, `llvm-option-inc-${version}.tar.xz`);
  const dir = path.join(work, "unpacked");
  fs.mkdirSync(dir, { recursive: true });
  common.run("tar", ["-C", dir, "-xJf", archive]);
  const stage = path.join(work, "stage", "llvm-option-inc");
  fs.mkdirSync(stage, { recursive: true });
  fs.renameSync(path.join(dir, "llvm-option-inc", "include"), path.join(stage, "include"));
  packages.push({
    name: "llvm-option-inc",
    stage,
    license: "Apache-2.0 WITH LLVM-exception",
    summary: "The option tables of clang, lld, llvm-lib and llvm-dlltool, generated by TableGen",
  });
}

/// One recipe per package: the staged tree copied into $PREFIX as it is,
/// no relocation, no prefix detection (nothing in it names a prefix).
for (const p of packages) {
  const recipe = path.join(`${p.stage}.recipe`, "recipe.yaml");
  fs.mkdirSync(path.dirname(recipe), { recursive: true });
  fs.writeFileSync(recipe, [
    "package:",
    `  name: ${p.name}`,
    `  version: "${version}"`,
    "source:",
    `  - path: ${JSON.stringify(p.stage)}`,
    "    use_gitignore: false",
    "build:",
    `  number: ${values.build}`,
    ...(p.subdir ? [] : ["  noarch: generic"]),
    "  script:",
    `    - cp -a . "$PREFIX/"`,
    "  dynamic_linking:",
    "    binary_relocation: false",
    "    overlinking_behavior: ignore",
    "    overdepending_behavior: ignore",
    "  prefix_detection:",
    "    ignore: true",
    "about:",
    "  homepage: https://github.com/clice-io/xclang",
    "  repository: https://github.com/clice-io/xclang",
    `  license: ${JSON.stringify(p.license)}`,
    `  summary: ${JSON.stringify(p.summary)}`,
    "",
  ].join("\n"));
  common.run(values["rattler-build"]!, [
    "build", "--recipe", recipe, "--output-dir", out, "--test", "skip", "--no-build-id",
    "--package-format", `conda:${values.compression}`,
    ...(p.subdir ? ["--target-platform", p.subdir] : []),
  ]);
  /// What rattler-build leaves behind is a copy of the package: gone, or
  /// six hosts do not fit on a CI machine's disk.
  fs.rmSync(p.stage, { recursive: true, force: true });
  fs.rmSync(path.join(out, "bld"), { recursive: true, force: true });
  fs.rmSync(path.join(out, "src_cache"), { recursive: true, force: true });
}

for (const subdir of fs.readdirSync(out).filter((d) => fs.statSync(path.join(out, d)).isDirectory())) {
  for (const file of fs.readdirSync(path.join(out, subdir)).filter((f) => f.endsWith(".conda"))) {
    console.log(`${(fs.statSync(path.join(out, subdir, file)).size / 1048576).toFixed(0).padStart(5)} MB  ${subdir}/${file}`);
  }
}
