# Cross-compile for macOS from another host, with an xclang tree and an SDK
# unpacked by vendor-sdk.py:
#   -DCMAKE_TOOLCHAIN_FILE=sdk/darwin.cmake -DXCLANG_ROOT=<xclang>
#   -DMACOS_SDK=<sdk> -DMACOS_ARCH=arm64|x86_64
foreach(var XCLANG_ROOT MACOS_SDK MACOS_ARCH)
    if(NOT ${var})
        message(FATAL_ERROR "sdk/darwin.cmake needs ${var}")
    endif()
endforeach()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES XCLANG_ROOT MACOS_SDK MACOS_ARCH)

set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR ${MACOS_ARCH})
set(CMAKE_OSX_ARCHITECTURES ${MACOS_ARCH} CACHE STRING "")
set(CMAKE_OSX_SYSROOT ${MACOS_SDK} CACHE PATH "")
set(CMAKE_OSX_DEPLOYMENT_TARGET 13.0 CACHE STRING "")

if(CMAKE_HOST_WIN32)
    set(_exe ".exe")
endif()
set(_bin "${XCLANG_ROOT}/bin")
set(CMAKE_C_COMPILER "${_bin}/clang${_exe}")
set(CMAKE_CXX_COMPILER "${_bin}/clang++${_exe}")
set(CMAKE_OBJC_COMPILER "${_bin}/clang${_exe}")
set(CMAKE_OBJCXX_COMPILER "${_bin}/clang++${_exe}")
foreach(lang C CXX OBJC OBJCXX ASM)
    set(CMAKE_${lang}_COMPILER_TARGET ${MACOS_ARCH}-apple-macos)
endforeach()
set(CMAKE_AR "${_bin}/llvm-ar${_exe}")
set(CMAKE_RANLIB "${_bin}/llvm-ranlib${_exe}")
set(CMAKE_NM "${_bin}/llvm-nm${_exe}")
set(CMAKE_STRIP "${_bin}/llvm-strip${_exe}")
set(CMAKE_OBJDUMP "${_bin}/llvm-objdump${_exe}")
set(CMAKE_LIBTOOL "${_bin}/llvm-libtool-darwin${_exe}")
set(CMAKE_LIPO "${_bin}/llvm-lipo${_exe}")
set(CMAKE_INSTALL_NAME_TOOL "${_bin}/llvm-install-name-tool${_exe}")
set(CMAKE_OTOOL "${_bin}/llvm-otool${_exe}")
set(CMAKE_DSYMUTIL "${_bin}/dsymutil${_exe}")
set(CMAKE_LINKER "${_bin}/ld64.lld${_exe}")

set(CMAKE_FIND_ROOT_PATH ${MACOS_SDK})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
